

################################
#### Download
################################
# fasterq-dump
download_fastq_pe:
  params: ''
  threads: 6
  retries: 5

download_fastq_se:
  params: ''
  threads: 6
  retries: 5

download_fastq_long:
  params: ''
  threads: 6
  retries: 5


################################
#### Index reference genome
################################
# BWA-MEM2
ref_DNA_mapping_index:
  params: ''

# STAR
ref_RNA_mapping_index:
  params: ''
  threads: 1

# pbmm2
ref_DNA_longRead_mapping_index:
  params: ''
ref_RNA_longRead_mapping_index:
  params: ''


################################
#### Trimming
################################
# fastp DNA paired-end
trimming_DNA_pe:
  params: ''
  threads: 16

# fastp DNA single-end
trimming_DNA_se:
  params: ''
  threads: 16

# fastp DNA long read
trimming_DNA_long:
  params: '--disable_quality_filtering --length_required 500'
  threads: 16

# fastp RNA paired-end
trimming_RNA_pe:
  params: ''
  threads: 16

# fastp RNA single-end
trimming_RNA_se:
  params: ''
  threads: 16

# fastp RNA long read
trimming_RNA_long:
  params: '--disable_quality_filtering --length_required 500'
  threads: 16


################################
#### Kmer analysis
################################
# Shared across all k-mer analysis jobs (to ensure consistency)
kmer_analysis:
  kmer: 21
  min_count: 1
  max_count: 10000

# KMC build k-mer database
kmer_analysis_createDB:
  params: ''
  memory: 64 #GB
  threads: 24

# Smudgeplot k-mer pairs
kmer_analysis_smudgeplot_pairs:
  memory: 24 #GB

# GenomeScope2 plotting
kmer_analysis_GenomeScope2:
  params: ''

# Smudgeplot plotting
kmer_analysis_Smudgeplot:
  params: ''


################################
#### Cross Mapping
################################
# BWA-MEM2
crossMapping_DNA_pe:
  mapping_params: ''
  sort_params: ''
  stats_params: ''
  mapping_threads: 24
  mapping_memory: 40 # GB
  sort_threads: 6
  sort_memory: 1 # GB
  stats_threads: 2

crossMapping_DNA_se:
  mapping_params: ''
  sort_params: ''
  stats_params: ''
  mapping_threads: 24
  mapping_memory: 40 # GB
  sort_threads: 6
  sort_memory: 1 # GB
  stats_threads: 2

# STAR
crossMapping_RNA_pe:
  sjdbOverhang: 150
  mapping_params: ''
  stats_params: ''
  mapping_threads: 24
  mapping_memory: 20 # GB
  stats_threads: 2

crossMapping_RNA_se:
  sjdbOverhang: 150
  mapping_params: ''
  stats_params: ''
  mapping_threads: 24
  mapping_memory: 20 # GB
  stats_threads: 2

# Long reads
crossMapping_DNA_long:
  mapping_params: ''
  sort_params: ''
  stats_params: ''
  mapping_threads: 24
  mapping_memory: 20 # GB
  sort_threads: 6
  sort_memory: 1 # GB
  stats_threads: 2

crossMapping_RNA_long:
  mapping_params: ''
  sort_params: ''
  stats_params: ''
  mapping_threads: 24
  mapping_memory: 20 # GB
  sort_threads: 6
  sort_memory: 1 # GB
  stats_threads: 2


################################
#### Kmer analysis
################################
# Shared across all k-mer jobs (to ensure con consistency)
kmer_analysis:
  kmer: 21
  min_count: 1
  max_count: 10000

# KMC build k-mer database
kmer_analysis_createDB:
  params: ''
  memory: 64 #GB
  threads: 24


################################
#### Mapping
################################
# BWA-MEM2
mapping_DNA_pe:
  mapping_params: ''
  sort_params: ''
  mapping_threads: 24
  mapping_memory: 40 # GB
  sort_threads: 6
  sort_memory: 1 # GB

mapping_DNA_se:
  mapping_params: ''
  sort_params: ''
  mapping_threads: 24
  mapping_memory: 40 # GB
  sort_threads: 6
  sort_memory: 1 # GB

# STAR
mapping_RNA_pe:
  sjdbOverhang: 150
  mapping_params: '--twopassMode Basic'
  mapping_threads: 24
  mapping_memory: 20 # GB

mapping_RNA_se:
  sjdbOverhang: 150
  mapping_params: '--twopassMode Basic'
  mapping_threads: 24
  mapping_memory: 20 # GB

# Long reads
mapping_DNA_long:
  mapping_params: ''
  sort_params: ''
  mapping_threads: 24
  mapping_memory: 20 # GB
  sort_threads: 6
  sort_memory: 1 # GB

mapping_RNA_long:
  mapping_params: ''
  sort_params: ''
  mapping_threads: 24
  mapping_memory: 20 # GB
  sort_threads: 6
  sort_memory: 1 # GB

# Samtools merge
mapping_merge:
  params: ''
  merge_threads: 8
  view_threads: 2


################################
#### Variant calling
################################
# run_deepvariant
calling_variants:
  params: ''
  threads: 8
  memory: 30 # GB

# bcftools index of merged VCF
calling_VCFs_index:
  params: ''
  threads: 8

# bcftools merge final VCFs
calling_merge_VCFs:
  threads: 48
  memory: 350 #GB
  params: ''

# Filter final merged file
calling_filter_VCFs:
  # Variables for plotting
  maf: 0.05
  miss: 1.0
  qual: 35
  min_depth: 10
  max_depth: 60
  # Varibale for filtering using vcftools
  filter: '--remove-indels --maf 0.05 --max-missing 1.0 --min-meanDP 10 --max-meanDP 60 --minDP 10 --maxDP 60 --minQ 35'


################################
#### Relatedness
################################
# 
relatedness_vcftools_relatedness2:
  params: ''

relatedness_vcf_clone_detect:
  threshold: 95.0

relatedness_ANGSD_for_NgsRelate:
  params: ''
  threads: 2
  memory: 50

relatedness_NgsRelate:
  params: ''
  threads: 2

relatedness_plink_Admixture:
  Kmin: 2
  Kmax: 20
  threads: 18


################################
#### Ploidy
################################
# nQuire
ploidy_nQuire:
  create_params: ''
  denoise_params: ''
  lrdmodel_params: ''
  coverage_params: ''
  min_quality: 20
  min_coverage: 20
  threads: 48


################################
#### QC
################################
# FastQC
qc_FastQC:
  params: ''
  mem_mb: 512
  threads: 1

# Samtools stats
qc_samtools_stats:
  params: ''

# qualimap
qc_qualimap:
  params: ''
  memory: 8 # GB

# bcftools stats
qc_bcftools_stats:
  params: ''

# MultiQC
qc_multiqc_reads:
  params: ''
qc_multiqc_calls:
  params: ''
qc_multiqc_crossMapping:
  params: ''


