

################################
#### Download
################################
# fasterq-dump
download_fastq_pe:
  params: ''
  threads: 6
  retries: 5

download_fastq_se:
  params: ''
  threads: 6
  retries: 5

download_fastq_long:
  params: ''
  threads: 6
  retries: 5


################################
#### Index reference genome
################################
# BWA-MEM2
ref_DNA_mapping_index:
  params: ''

# STAR
ref_RNA_mapping_index:
  params: ''
  threads: 1

# pbmm2
ref_DNA_longRead_mapping_index:
  params: ''
ref_RNA_longRead_mapping_index:
  params: ''


################################
#### Trimming
################################
# fastp DNA paired-end
trimming_DNA_pe:
  params: ''
  threads: 16

# fastp DNA single-end
trimming_DNA_se:
  params: ''
  threads: 16

# fastp DNA long read
trimming_DNA_long:
  params: ''
  threads: 16

# fastp RNA paired-end
trimming_RNA_pe:
  params: ''
  threads: 16

# fastp RNA single-end
trimming_RNA_se:
  params: ''
  threads: 16

# fastp RNA long read
trimming_RNA_long:
  params: ''
  threads: 16


################################
#### Kmer analysis
################################
# Shared across all k-mer analysis jobs (to ensure consistency)
kmer_analysis:
  kmer: 21
  min_count: 1
  max_count: 10000

# KMC build k-mer database
kmer_analysis_createDB:
  params: ''
  memory: 64 #GB
  threads: 24

# Smudgeplot k-mer pairs
kmer_analysis_smudgeplot_pairs:
  memory: 24 #GB

# GenomeScope2 plotting
kmer_analysis_GenomeScope2:
  params: ''

# Smudgeplot plotting
kmer_analysis_Smudgeplot:
  params: ''


################################
#### Cross Mapping
################################
# BWA-MEM2
crossMapping_DNA_pe:
  mapping_params: ''
  sort_params: ''
  stats_params: ''
  threads: 24
  memory: 20 # GB

crossMapping_DNA_se:
  mapping_params: ''
  sort_params: ''
  stats_params: ''
  threads: 24
  memory: 20 # GB

# STAR
crossMapping_RNA_pe:
  sjdbOverhang: 150
  mapping_params: ''
  stats_params: ''
  threads: 24
  memory: 20 # GB

crossMapping_RNA_se:
  sjdbOverhang: 150
  mapping_params: ''
  stats_params: ''
  threads: 24
  memory: 20 # GB

# Long reads
crossMapping_DNA_long:
  mapping_params: ''
  sort_params: ''
  stats_params: ''
  threads: 24
  memory: 20 # GB

crossMapping_RNA_long:
  mapping_params: ''
  sort_params: ''
  stats_params: ''
  threads: 24
  memory: 20 # GB


################################
#### Kmer analysis
################################
# Shared across all k-mer jobs (to ensure con consistency)
kmer_analysis:
  kmer: 21
  min_count: 1
  max_count: 10000

# KMC build k-mer database
kmer_analysis_createDB:
  params: ''
  memory: 64 #GB
  threads: 24


################################
#### Mapping
################################
# BWA-MEM2
mapping_DNA_pe:
  mapping_params: ''
  sort_params: ''
  threads: 24
  memory: 20 # GB

mapping_DNA_se:
  mapping_params: ''
  sort_params: ''
  threads: 24
  memory: 20 # GB

# STAR
mapping_RNA_pe:
  sjdbOverhang: 150
  mapping_params: '--twopassMode Basic'
  threads: 24
  memory: 20 # GB

mapping_RNA_se:
  sjdbOverhang: 150
  mapping_params: '--twopassMode Basic'
  threads: 24
  memory: 20 # GB

# Long reads
mapping_DNA_long:
  mapping_params: ''
  sort_params: ''
  threads: 24
  memory: 20 # GB

mapping_RNA_long:
  mapping_params: ''
  sort_params: ''
  threads: 24
  memory: 20 # GB

# Samtools merge
mapping_merge:
  params: ''
  threads: 8


################################
#### Variant calling
################################
# run_deepvariant
calling_variants:
  params: ''
  threads: 8
  memory: 20 # GB

# bcftools index of merged VCF
calling_VCFs_index:
  params: ''
  threads: 8

# bcftools merge final VCFs
calling_merge_VCFs:
  params: ''

# Filter final merged file
calling_filter_VCFs:
  filter: '--remove-indels --min-meanDP 10 --max-missing 1.0'


################################
#### Relatedness
################################
# 
relatedness_vcftools_relatedness2:
  params: ''

relatedness_vcf_clone_detect:
  threshold: 95.0

relatedness_ANGSD_for_NgsRelate:
  params: ''
  threads: 8

relatedness_NgsRelate:
  params: ''
  threads: 8

relatedness_ANGSD_for_PCAngsd:
  params: ''
  threads: 8

relatedness_PCAngsd_IndAlleleFreq:
  params: ''
  threads: 8

relatedness_PCAngsd_WithOutIndAlleleFreq:
  params: ''
  threads: 8

relatedness_PCAngsd_Admixture:
  params: ''
  threads: 8


################################
#### Ploidy
################################
# nQuire
ploidy_nQuire:
  create_params: ''
  denoise_params: ''
  lrdmodel_params: ''
  coverage_params: ''
  min_quality: 1
  min_coverage: 10
  threads: 8


################################
#### QC
################################
# FastQC
qc_FastQC:
  params: ''
  threads: 1

# Samtools stats
qc_samtools_stats:
  params: ''

# qualimap
qc_qualimap:
  params: ''

# bcftools stats
qc_bcftools_stats:
  params: ''

# MultiQC
qc_multiqc_reads:
  params: ''
qc_multiqc_calls:
  params: ''
qc_multiqc_crossMapping:
  params: ''


