# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.
from snakemake.utils import min_version

min_version("6.5")


report: "report/workflow.rst"


rule all:
	input:
		"results/merged_calls/all.vcf.gz",
		"results/qc/multiqc.html",
		"results/final/vcftools_relatedness2.tsv",
		"results/final/vcf_clone_detect.tsv",
		"results/final/NgsRelate.tsv",
		"results/final/PCAngsd.IndAlleleFreq.tsv",
		"results/final/PCAngsd.WithOutIndAlleleFreq.tsv",
		"results/final/PCAngsd.Admixture.tsv",
		"results/final/nQuire.tsv",


include: "rules/common.smk"
include: "rules/install_programs.smk"
include: "rules/ref.smk"
include: "rules/trimming.smk"
include: "rules/mapping.smk"
include: "rules/calling.smk"
include: "rules/qc.smk"
include: "rules/relatedness.smk"
include: "rules/ploidy.smk"
