# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.
from snakemake.utils import min_version

min_version("6.5")

report: "report/workflow.rst"

include: "rules/common.smk"
include: "rules/install_programs.smk"
include: "rules/ref.smk"
include: "rules/download.smk"
include: "rules/trimming.smk"
include: "rules/mapping.smk"
include: "rules/calling.smk"
include: "rules/qc.smk"
include: "rules/cross-mapping.smk"
include: "rules/relatedness.smk"
include: "rules/ploidy.smk"
include: "rules/annotations.smk"
include: "rules/plotting.smk"

localrules:
	all,
	full_workflow, 
	cross_mapping,


rule all:
	input:
		"cross_mapping",
		"full_workflow"


rule cross_mapping:
	input:
		rules.qc_multiqc_crossMapping.output,
		rules.plotting_cross_mapping_results.output,
	output:
		temp(touch("cross_mapping")),


rule full_workflow:
	input:
		rules.format_filtered_VCF.output,
		rules.qc_multiqc_reads.output,
		rules.qc_multiqc_variant_calls.output,
		rules.format_results_vcftools_relatedness2.output,
		rules.format_results_vcf_clone_detect_counts.output,
		rules.format_results_vcf_clone_detect_groups.output,
		rules.format_results_NgsRelate.output,
		rules.format_results_PCAngsd_IndAlleleFreq.output,
		rules.format_results_PCAngsd_WithOutIndAlleleFreq.output,
		rules.format_results_PCAngsd_Admixture.output,
		rules.format_nQuire_results.output,
		rules.format_annotations.output,
		rules.plotting_ANGSD_results.output.html,
		rules.plotting_vcf_clone_detect_results.output.html,
		rules.plotting_vcftools_relatedness2_results.output.html,
	output:
		temp(touch("full_workflow")),


