---
title: "Plot `ANGSD` results"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
  highlight: tango
  number_sections: no
  theme: default
  toc: yes
  toc_depth: 3
  toc_float:
    collapsed: no
    smooth_scroll: yes
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# Setup R env. Load packages and set default image export formats, size and resolution.
library(tibble)
library(ggplot2)
library(ggdendro)
library(heatmaply)
library(reshape2)
library(RColorBrewer)
library(cowplot)
options(scipen = 999) #Prevent scientific notation
```

```{r file_names, echo=FALSE, message=FALSE}
# File names and important variables.
annot.file <- "Annotations.tsv"
admixture.file <- "PCAngsd.Admixture.tsv"
allelFreqs.file <- "PCAngsd.IndAlleleFreq.tsv"
```

```{r load_metadata, echo=FALSE, message=FALSE}
#*Annotations*
annot <- read.table(annot.file, header=T, sep='\t', comment.char='') %>% 
  column_to_rownames(var = "sample_id")
```

```{r color_palette, echo=FALSE, message=FALSE}
#*Color palette*
annot.labels <- annot[c("group_id","best_ploidy_model")]
annot.cols <- annot[c("group_id_color","best_ploidy_model_color")] %>% 
  rename("group_id" = "group_id_color") %>% 
  rename("best_ploidy_model" = "best_ploidy_model_color")

# Get color combinations for plotting
palette <- as.character(c(
  annot.cols$group_id, 
  annot.cols$best_ploidy_model
))
names(palette) <- as.character(c(
  annot.labels$group_id, 
  annot.labels$best_ploidy_model
))
palette <- palette[!duplicated(palette)]
```

```{r load_Admixture_data, echo=FALSE, message=FALSE}
#*Admixture*
admixture <- read.table(admixture.file, header=T, sep='\t', comment.char='', check.names=FALSE) %>% 
  column_to_rownames(var = "sample_id")
```

```{r load_IndAlleleFreq_data, echo=FALSE, message=FALSE}
#*IndAlleleFreq*
allelFreqs <- read.table(allelFreqs.file, header=T, sep='\t', comment.char='', check.names=FALSE) %>% 
  column_to_rownames(var = "sample_id")
```


``` {r func_cluster_plot, echo=FALSE, message=FALSE}
# A function that wraps up all the functions required to parse and plot the input data.
# Will use the supplied hclust object to create dendrogram and order bars or will perform clustering itself.
cluster_plot <- function(data, samples, selected_columns, 
                         plot.dendro=NULL, colors=NULL,
                         dist.method="euclidean", hclust.method="complete",
                         x.label.font.size=5, legend.size.scale=0.5,
                         legend.title="Groups",
                         rel_heights=c(0.3, 1.0, 0.3)) {
  # Code modified from: https://stackoverflow.com/questions/44646488/stacked-bar-plot-with-hierarchical-clustering-dendrogram
  
  #########################
  #### Cluster samples ####
  #########################
  if(is.null(plot.dendro)) {
    d <- dist(as.matrix(data), method=dist.method)
    hc <- hclust(d, method=hclust.method)
    plot.dendro <- as.dendrogram(hc)
  }
  
  ##############
  #### Plot ####
  ##############
  # Convert dendrogram to segment data
  dend_data <- dendro_data(plot.dendro, type="rectangle")
  segment_data <- dend_data[["segments"]]
  dend_labels <- gsub('\'', '', dend_data$labels$label)

  # Sample positions df
  sample_pos_table <- with(dend_data$labels, 
                           data.frame(x_center = x, sample = as.character(label), width = 0.9))
  # X-axis limits
  axis_limits <- with(sample_pos_table, 
                      c(min(x_center - 0.5 * width), max(x_center + 0.5 * width))) + 
                      0.1 * c(-1, 1) # extra spacing: 0.1
  
  # Plot clustering dendrogram
  p.dendr <- ggplot(segment_data) +
    geom_segment(aes(x = x, y = y, xend = xend, yend = yend)) +
    scale_y_continuous(expand = c(0, 0, 0, 0.1)) + 
    scale_x_continuous(breaks = sample_pos_table$x_center, 
                       labels = NULL, 
                       limits = axis_limits, 
                       expand = c(0, 0)) + 
    labs(x = "", y = "Distance", colour = "", size = "") +
    theme_bw() + 
    theme(panel.grid.minor=element_blank(),
          panel.grid.major=element_blank(),
          plot.margin=unit(c(0,0,0,0), "mm"))
  
  # Plot bar chart
  p.barplot <- data %>%
    rownames_to_column() %>%
    arrange(as.character(factor(rowname, levels = dend_labels)), dend_labels) %>%
    column_to_rownames("rowname") %>%
    as.matrix() %>%
    melt() %>%
    rename(Sample=Var1, ITS2type=Var2, Abundance=value) %>%
    # Plot bar chart
    ggplot(aes(x=Sample, y=Abundance, fill=ITS2type)) +
      geom_bar(position="stack", stat="identity") +
      scale_y_continuous(expand = c(0, 0)) +
      scale_fill_manual(values = colorRampPalette(brewer.pal(12,"Paired"))(12)) +
      labs(x = "", y = "Frequency", fill=legend.title) +
      theme_bw() +
      theme(axis.text.x=element_blank(),
            legend.key.height= unit(2*legend.size.scale, 'mm'),
            legend.key.width= unit(2*legend.size.scale, 'mm'),
            legend.title = element_text(size=4*legend.size.scale),
            legend.text = element_text(size=4*legend.size.scale),
            plot.margin=unit(c(0,0,0,0), "mm")) +
      guides(fill=guide_legend(ncol=1))
  
  # Plot Meta Information about samples
  if(is.null(colors)) {
    colors <- rep(brewer.pal(brewer.pal.info["Set3", "maxcolors"], "Set3"), ceiling(nrow(samples)/12))
  }
  p.sampleInfo <- samples %>%
    select(all_of(selected_columns)) %>%
    rownames_to_column() %>% 
    arrange(as.character(factor(rowname, levels = dend_labels)), dend_labels) %>% 
    column_to_rownames("rowname") %>% 
    as.matrix() %>% 
    melt() %>% 
    rename(Sample=Var1, MetaInfo=Var2, Value=value) %>% 
    mutate(Count = 1) %>% 
    filter(MetaInfo!="PlugID") %>%
    ggplot(aes(x=Sample, y=Count, fill=Value)) + 
      geom_bar(position="stack", stat="identity") + 
      scale_y_continuous(expand = c(0, 0)) + 
      scale_fill_manual(values=colors) +
      labs(x = "Samples", y = "Meta Information", fill="") +
      theme_bw() +
      theme(axis.text.x=element_text(angle = 90, vjust = 0.5, hjust=1, size=x.label.font.size),
            axis.ticks.y=element_blank(),
            axis.text.y=element_blank(),
            legend.key.height= unit(2*legend.size.scale, 'mm'),
            legend.key.width= unit(2*legend.size.scale, 'mm'),
            legend.title = element_text(size=4*legend.size.scale),
            legend.text = element_text(size=4*legend.size.scale),
            plot.margin=unit(c(0,0,0,0), "mm")) +
      guides(fill=guide_legend(ncol=1))
  
  # Combine plots and print to screen
  comb <- plot_grid(p.dendr, p.barplot, p.sampleInfo, align = 'v', ncol = 1, axis = "lr", rel_heights = rel_heights)
  print(comb)
}
```


```{r plot_Admixture, echo=FALSE, message=FALSE}
# Plot Admixture results. Use the admixture matrix to generate the degdrogram and sample order.
cluster_plot(admixture, annot.labels, c("group_id", "best_ploidy_model"), colors=palette, x.label.font.size=2)
```


```{r load_PCAngsd_IndAllelFreq_data, echo=FALSE, message=FALSE}
# Generate eigen vectors.
C <- as.matrix(allelFreqs)
e <- eigen(C)
df <- as.data.frame(e$vectors)
rownames(df) <- rownames(C)
df <- cbind(df, annot.labels)
```


```{r plotly_PCAngsd_IndAllelFreq_PC1_PC2, echo=FALSE, message=FALSE}
# Plot PC1 and PC2 of PCAngsd results WITH estimated individual allele frequencies using the `plotly` package.
# group_id
p <- plot_ly(df, x=~V1, y=~V2, text=rownames(df), type = "scatter",
             mode="markers", color=~group_id, colors=palette, marker=list(size=11))
p <- layout(p,title="Without individual allele frequency - colored by group_id",
            xaxis=list(title="PC1"),
            yaxis=list(title="PC2"))
p

# Reef
p <- plot_ly(df, x=~V1, y=~V2, text=rownames(df), type = "scatter",
             mode="markers", color=~best_ploidy_model, colors=palette, marker=list(size=11))
p <- layout(p,title="Without individual allele frequency - colored by best_ploidy_model",
            xaxis=list(title="PC1"),
            yaxis=list(title="PC2"))
p
```


```{r ressionInfo, echo=FALSE, message=FALSE}
#sessionInfo()
```

