---
title: "Plot `vcf_clone_detect.py` results"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
  highlight: tango
  number_sections: no
  theme: default
  toc: yes
  toc_depth: 3
  toc_float:
    collapsed: no
    smooth_scroll: yes
---


```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# Setup R env. Load packages and set default image export formats, size and resolution.
library(tibble)
library(ggplot2)
library(heatmaply)
options(scipen = 999) #Prevent scientific notation
```


```{r data_file_names, echo=FALSE, message=FALSE}
# File names and important variables.
annotations.file <- "samples.genotyping.tsv"
colors.file <- "colors.tsv"
data.file <- "vcf_clone_detect.counts.tsv"
similarity.threshold <- <<<similarity.threshold>>>
```


```{r load_data_files, echo=FALSE, message=FALSE}
#*Data matrix*
data <- read.table(data.file, header=T, sep='\t', comment.char='', check.names=FALSE) %>%
  column_to_rownames(var = "sample_id")

#*Annotations matrix*
annotations <- read.table(annotations.file, header=T, sep='\t', comment.char='#', check.names=FALSE) %>%
  column_to_rownames(var = "sample_id") %>%
  select(-c("unit", "fq1", "fq2", "best_ploidy_model_num"))

#*Colors matrix*
tmp.colors <- read.table(colors.file, header=F, sep='\t', comment.char='', check.names=FALSE)
colors <- c(tmp.colors[,2])
names(colors) <- c(tmp.colors[,1])
```


```{r heatmap, echo=FALSE, message=FALSE}
# Sort rows for plotting using annotations (NOTE: Need to uncomment Rowv for this to take effect)
rownames.ordered <- annotations %>%
#  arrange(species, location, lib_type) %>% # Sort rows by selected annotation columns
#  filter(species=="Mcapitata") %>% # Plot only rows with specific annotations
  rownames()

# Plot matrix heatmap
heatmaply(
  data[rownames.ordered, ],
  plot_method = "plotly",
  width = 1000,
  height = 4000,
  row_side_colors=annotations[rownames.ordered,],
  col_side_colors=annotations[rownames.ordered,],
  row_side_palette=colors,
  col_side_palette=colors,
  side_color_colorbar_len=0.5,
  colorbar_xpos=1.05,
  colorbar_ypos=-0.3,
  column_text_angle=90,
  cexRow=1.0*(20/nrow(data)),
  cexCol=1.0*(20/nrow(data)),
  #scale="row", # Scale rows instead of using min and max of whole matrix
  #Rowv=FALSE, # Dont plot row dendrogram - Use row order in rownames.ordered
)
```


```{r similairty_density, echo=FALSE, message=FALSE}
vline <- function(x, text) {
  list(
    type = "line", 
    y0 = 0, 
    y1 = 1, 
    yref = "paper",
    x0 = x, 
    x1 = x, 
    line = list(color = "red")
  )
}

x <- na.omit(as.vector(t(data)))
fit <- density(x)
plot_ly(x = x, type = "histogram", name = "Histogram") %>% 
  add_trace(x = fit$x, y = fit$y, type = "scatter", mode = "lines", fill = "tozeroy", yaxis = "y2", name = "Density") %>% 
  layout(yaxis2 = list(overlaying = "y", side = "right"),
         shapes = list(vline(similarity.threshold))
         )
```


```{r ressionInfo, echo=FALSE, message=FALSE}
# Session Info
#sessionInfo()
```
