---
title: "Plot `vcftools --relatedness2` results"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
  highlight: tango
  number_sections: no
  theme: default
  toc: yes
  toc_depth: 3
  toc_float:
    collapsed: no
    smooth_scroll: yes
---


```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# Setup R env. Load packages and set default image export formats, size and resolution.
library(tibble)
library(ggplot2)
library(heatmaply)
options(scipen = 999) #Prevent scientific notation
```


```{r file_names, echo=FALSE, message=FALSE}
# File names and important variables.
annot.file <- "Annotations.tsv"
data.file <- "vcftools_relatedness2.tsv"
```


```{r load_metadata, echo=FALSE, message=FALSE}
#*Annotations*
annot <- read.table(annot.file, header=T, sep='\t', comment.char='') %>% 
  column_to_rownames(var = "sample_id")
```


```{r color_palette, echo=FALSE, message=FALSE}
#*Color palette*
annot.labels <- annot[c("group_id","best_ploidy_model")]
annot.cols <- annot[c("group_id_color","best_ploidy_model_color")] %>% 
  rename("group_id" = "group_id_color") %>% 
  rename("best_ploidy_model" = "best_ploidy_model_color")

# Get color combinations for plotting
palette <- as.character(c(
  annot.cols$group_id, 
  annot.cols$best_ploidy_model
))
names(palette) <- as.character(c(
  annot.labels$group_id, 
  annot.labels$best_ploidy_model
))
palette <- palette[!duplicated(palette)]
```


```{r load_pairwise_simScores, echo=FALSE, message=FALSE}
#*Data matrix*
data <- read.table(data.file, header=T, sep='\t', comment.char='', check.names=FALSE) %>% 
  column_to_rownames(var = "sample_id")
```


```{r heatmap, echo=FALSE, message=FALSE}
# Plot matrix heatmap
heatmaply(
  data,
  #plot_method = "plotly",
  col_side_colors=annot.labels[colnames(data),],
  row_side_colors=annot.labels[colnames(data),],
  row_side_palette=palette,
  col_side_palette=palette,
  column_text_angle=90,
  cexRow=0.2,
  cexCol=0.2,
)
```


```{r similairty_density, echo=FALSE, message=FALSE}
vline <- function(x, text) {
  list(
    type = "line",
    y0 = 0,
    y1 = 1,
    yref = "paper",
    x0 = x,
    x1 = x,
    line = list(color = "red")
  )
}

x <- na.omit(as.vector(t(data)))
fit <- density(x)
plot_ly(x = x, type = "histogram", name = "Histogram") %>% 
  add_trace(x = fit$x, y = fit$y, type = "scatter", mode = "lines", fill = "tozeroy", yaxis = "y2", name = "Density") %>% 
  layout(yaxis2 = list(overlaying = "y", side = "right"),
         shapes = list(
                       vline(1/2),
                       vline(1/4),
                       vline(1/8),
                       vline(1/16),
                       vline(0)
                      )
         )
```


```{r ressionInfo, echo=FALSE, message=FALSE}
# Session Info
#sessionInfo()
```
