samples: 'config/samples.tsv'
joint_calling_groups: 'config/joint_calling_groups.tsv'

ref:
    file: '.tests/data/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa.gz'

bwa_index:
  mem_mb: 369000

fastp_se:
  adapter: ''
  extra: '--correction'
  threads: 2

fastp_pe:
  adapter: ''
  extra: '--correction'
  threads: 2

bwa_mem2:
  extra: ''
  sort_extra: ''
  threads: 24

samtools_merge:
  params: ''
  threads: 8

samtools_index:
  params: ''

deepvariant:
  model: 'WGS'
  extra: ''
  params: ''
  threads: 8

deepvariant_gvcf:
  model: 'WGS'
  extra: ''
  params: ''
  threads: 8

glnexus:
  config: 'DeepVariantWGS'
  threads: 8

bcftools_index:
  extra: ''
  threads: 8

bcftools_merge:
  params: '--force-samples'

vcftools_filter:
  filter: ''
#  filter: '--remove-indels --min-meanDP 10 --max-missing 1.0'

vcftools_relatedness2:
  params: ''

vcf_clone_detect:
  threshold: 95.0
  params: ''

angsd_for_NgsRelate:
  params: ''
  threads: 8

NgsRelate:
  params: ''
  threads: 8

angsd_for_PCAngsd:
  params: ''
  threads: 8

PCAngsd_IndAlleleFreq:
  params: ''
  threads: 8

PCAngsd_WithOutIndAlleleFreq:
  params: ''
  threads: 8

PCAngsd_Admixture:
  params: ''
  threads: 8

nQuire:
  create_params: ''
  denoise_params: ''
  lrdmodel_params: ''
  min_quality: 20
  min_coverage: 20
  threads: 8

