################################
#### Config for genotyping
################################

project_name: 'species1_genotyping'

samples: 'config/samples.tsv'

ref_genomes:
  'genome2': 'path/to/genome2.fa.gz'


# Filter final merged file
calling_filter_VCFs:
  filter: '--remove-indels --min-meanDP 10 --max-missing 1.0'


# Percent similarity cutoff to use for vcf_clone_detect.py
relatedness_vcf_clone_detect:
  threshold: 95.0


# nQuire
ploidy_nQuire:
  min_quality: 20
  min_coverage: 20


