samples: 'config/samples.tsv'
joint_calling_groups: 'config/joint_calling_groups.tsv'

ref:
    file: '.tests/data/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa.gz'

bwa_index:
  mem_mb: 369000

fastp_se:
  adapter: ''
  extra: '--correction'
  threads: 2

fastp_pe:
  adapter: ''
  extra: '--correction'
  threads: 2

bwa_mem2:
  extra: ''
  sort_extra: ''
  threads: 24

samtools_merge:
  params: ''
  threads: 8

samtools_index:
  params: ''

deepvariant:
  model: 'wgs'
  extra: ''
  params: ''
  threads: 8

deepvariant_gvcf:
  model: 'wgs'
  extra: ''
  params: ''
  threads: 8

glnexus:
  config: 'DeepVariantWGS'
  threads: 8

bcftools_index:
  extra: ''
  threads: 8

bcftools_merge:
  params: '--force-samples'

bcftools_filter:
  filter: ''
