################################
#### Config for Cross Mapping
################################

project_name: 'sample_CrossMapping'

samples: 'config/samples.tsv'

ref_genomes:
  'genome1': 'path/to/genome1.fa'
  'genome2': 'path/to/genome2.fa.gz'


