################################
#### Config for Calling Variants
################################

# Name of project
project_name: 'species1_Genotyping'

# Path to sample manifest
samples: 'config/samples.tsv'

# Reference genome name : absolute path (can be gzipped)
ref_genomes:
  'genome2': 'path/to/genome2.fa.gz'

