$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  samples:
    type: string
  genomes:
    type: string
  ref_name:
    type: string
  project_name:
    type: string


# entries that have to be in the config file for successful validation
required:
  - samples
  - ref_genomes
  - project_name
